const cp=require('child_process')
// cp.execSync('calc')
// cp.execSync('start chrome')
// cp.execSync('start chrome https://www.scaler.com/topics/course/nodejs/video/973/')
console.log('output '+cp.execSync('node demo.js'))