const path=require('path')
let ext=path.ext('C:\\Users\\IT LAB-II\\Desktop\\JV\\node js course\\Node Module System\\f1.txt')
console.log(ext)
let basename=path.basename('C:\Users\IT LAB-II\Desktop\JV\node js course\Node Module System\f1.txt')
console.log(basename)
console.log(__filename)
console.log(__dirname)